"""empty message

Revision ID: 4b177db70fb7
Revises: 216d405ee6e0
Create Date: 2025-09-29 17:45:57.929176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b177db70fb7'
down_revision = '216d405ee6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book_instances',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books_table.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.drop_table('copies_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copies_table',
    sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books_table.isbn'], name=op.f('copies_table_isbn_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('copies_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('isbn', name=op.f('copies_table_pkey'))
    )
    op.drop_table('Book_instances')
    # ### end Alembic commands ###
